name: emma-pay
version: 0.1.0
summary: Emma Pay
description: Super Cool App that does everything!

confinement: strict
base: core22
grade: stable

architectures:
  - build-on: arm64
    buid-for: arm64
  - build-on: amd64
    build-for: amd64

apps:
  emma-pay:
    command: emmapay
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network

parts:
  emma-pay:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application