name: emma-pay
version: 0.1.0
summary: Emma Pay
description: Super Cool App that does everything!

confinement: strict
base: core18
grade: stable

slots:
  dbus-emma-pay: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: io.emmalabs.emma_pay # adjust accordingly to your app name and
    
apps:
  emma-pay:
    command: emma-pay
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-emma-pay
parts:
  emma-pay:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application